### ISSUE TITLE
mailer template mistake produce gross errors

### ISSUE THREAD

**Issue by anderbubble** [ResearchComputing/RCAMP#160]
It would be nice if templates were a bit more fault-tolerant, or had some edit-time error checking. This may be a limitation of the tempting library; but maybe they could at least try rendering the template before saving?

**Comment by zebulasampedro** [comment]
@anderbubble Just to be clear: the scope of this issue is to make sure that there are no syntax errors in the Mailer Template prior to saving the model, correct? Are we hoping to simply make sure the template won't error out down the road when RCAMP tries to send it, or are we hoping to make sure prior to save that the template will render _as expected_?

**Comment by anderbubble** [comment]
@zebulasampedro actually, I think the bigger issue is the mailers causing crashes rather than simply not woking. For the sake of the milestone, I'd say putting some `try: except:` around the actual mailer, and flashing an error message if the mailer fails or fails to render, might be sufficient for now.

**Comment by anderbubble** [comment]
@zebulasampedro can you describe what the fix does?

**Comment by zebulasampedro** [comment]
@anderbubble There are three components to this fix:
* `MailNotifier` objects now validate template field syntax prior to saving.
* The Mail Notifier admin will raise a `ValidationError` if the user tries to save a syntactically incorrect template. This error message will specify which field is failing.
* Basic error handling has been added to the Mail Notifier `send` method. A broken notifier will fail gracefully, and an associated Mail Log will be saved. This log will preserve the message context in the `email_object` field.
