### ISSUE TITLE
Replace "I want to create a new project" wording on account request page

### ISSUE THREAD

**Issue by pruprecht** [ResearchComputing/RCAMP#162]
Should instead say "I am not affiliated with an existing project".

**Comment by jafrahm** [comment]
IMO this page:
"https://rcamp.rc.colorado.edu/"
when you are not logged in should say: 
Sign In to request compute access or manage your Projects.
(or... wordsmithing suggestions welcome)

Avoiding "Login" reduces the chance of that button being construed as access to a shell or system interface.

When you are logged in it says:
---
Manage your projects
The Project Management Page allows you to review, edit, and request time against your projects.
---
We should indicate that the link also directs you to the mailto link for General access.  Jonathon said something about building out that mailto: to load the Subject, etc.  it'd be interesting to know what can be achieved there to get consistency from the results.  If that's an option we can gen an issue for that.

When logged in it seems like this page is a doubling of the other page however but maybe that is due to there being only one choice currently.  I'd address this by putting the mailto: for General access on this page as well as the link to the Project and Allocation management interfaces.

**Comment by anderbubble** [comment]
@jafrahm I agree with everything you've said, and particularly like the idea of using "sign in" to refer to the portal to distinguish it from "log in" for the system. These comments are more relevant to #156 and #165, so I've copied the bits of your comments there, and also created #173 to check on the mailto: link headers.
