### ISSUE TITLE
Server Error (500) when creating new project

### ISSUE THREAD

**Issue by pruprecht** [ResearchComputing/RCAMP#175]
I filled out the project ~~request~~ creation form at https://rcamp.rc.colorado.edu/projects/create at 1:35pm Feb 8 and received a Server Error.

**Comment by pruprecht** [comment]
Also, I was logged in as ruprech@local at the time, if that matters.

**Comment by anderbubble** [comment]
I think the issue is that the `ProjectCreated` notifier is trying to send a message to `project.pi_emails`; but this field stores a `repr()` of a Python list, not a list itself or a comma-separated string.

Let's check on the internal formatting, how it's presented to the mailer, and document that at https://wiki.rc.colorado.edu/rcops/index.php/RCAMP#Email_Notifications.

**Comment by zebulasampedro** [comment]
The `project.pi_emails` field stores a Python list. The issue however is that the list is being passed directly into a template substitution `{{ project.pi_emails }}` in the `ProjectCreated` notifier. This substitution is coercing the list to its string representation.

For the _mailto_ field, instead of
```
{{ project.pi_emails }}
```
the template should instead be
```
{% for email in project.pi_emails %}{{ email }},{% endfor %}
```

In an effort to offer more clarity to the data passed to notifiers, I have revised the wiki describing the [mailer signals](https://wiki.rc.colorado.edu/rcops/index.php/RCAMP#Event_Data). The docs now illustrate the available attributes, as well as their types.

**Comment by anderbubble** [comment]
@zebulasampedro would `','.join(project.pi_emails)` also work?

**Comment by zebulasampedro** [comment]
@anderbubble If you wanted to go the join route you'd have to use the following syntax
```
{{ project.pi_emails|join:"," }}
```

**Comment by anderbubble** [comment]
@jafrahm I've updated the mailer to send mail to `{{ project.pi_emails|join:"," }}` (in the production portals.rc.colorado.edu). Can you test and see if this is working now?
