### ISSUE TITLE
add cluster name to name of automatically created allocations

### ISSUE THREAD

**Issue by pruprecht** [ResearchComputing/RCAMP#203]
Automatically-created allocation account names should be in the form ucb-summit3 (or csu-summit3), instead of just ucb3.  This will avoid potential account name collisions on future clusters, and will just be easier for both admins and users to understand.

If this is a straightforward change, I'd ask for it to be a higher priority because we'd like to have consistent allocation account names as soon as we start creating them.

**Comment by anderbubble** [comment]
@zebulasampedro right now, a project like `ucb1` will get an allocation id like `ucb1_1`. The allocation id there is what we should be changing the template for, so that it creates `ucb1_summit1`, for example.

For now I'd be fine with just setting a static prefix and not worrying about multiple cluster support, since we're only allocating one cluster right now anyway. But if you already have access to the name `summit` at allocation-id-assignment time, might as well use it.
